<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @category    ViraXpress
 * @package     ViraXpress_Rma
 * @author      ViraXpress
 * @copyright   © 2026 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// @phpcs:disable Generic.Files.LineLength
/** @var $block \Magento\Config\Block\System\Config\Form\Field */
$element = $block->getElement();
$elementId = $element->getHtmlId();
$elementName = $element->getName();
$cssClass = $block->getData('list_class') ?: 'generic-list';
$values = $element->getValue() ? explode(',', $element->getValue()) : [];
?>
<div id="<?= $escaper->escapeHtmlAttr($elementId) ?>_wrapper">
    <ul class="<?= $escaper->escapeHtmlAttr($cssClass) ?> generic-list " id="<?= $escaper->escapeHtmlAttr($elementId) ?>_list">
        <?php foreach ($values as $value): ?>
            <?php $value = trim($value); if ($value !== ''): ?>
                <li class="list-add-input">
                    <input type="text" name="<?= $escaper->escapeHtmlAttr($elementName) ?>[]" value="<?= $escaper->escapeHtmlAttr($value) ?>" />
                    <button type="button" class="remove-field">Remove</button>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <div class="list-add-input">
        <input type="text" id="<?= $escaper->escapeHtmlAttr($elementId) ?>_new_value" />
        <button type="button" class="add-field">Add</button>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#<?= $escaper->escapeHtmlAttr($elementId) ?>_wrapper": {
        "ViraXpress_Rma/js/list-field": {
            "elementId": "<?= $escaper->escapeHtmlAttr($elementId) ?>",
            "elementName": "<?= $escaper->escapeHtmlAttr($elementName) ?>"
        }
    }
}
</script>
